/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/remote.glb -o src/Remote.jsx 
Author: 1-3D.com (https://sketchfab.com/1-3D.com)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/tv-remote-control-554dd608873842068fed78959831bad1
Title: Tv remote control
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Remote(props) {
  const { nodes, materials } = useGLTF('/remote.glb')
  return (
    <group castShadow {...props} dispose={null}>
      <group castShadow rotation={[-Math.PI / 2, 0, 0]}>
        <mesh castShadow geometry={nodes.Object_2.geometry} material={materials.base} />
        <mesh castShadow geometry={nodes.Object_3.geometry} material={materials.basemate} />
        <mesh castShadow geometry={nodes.Object_4.geometry} material={materials.buttons} />
      </group>
    </group>
  )
}

useGLTF.preload('/remote.glb')
