/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/round_table.glb -o src/table.jsx 
Author: shedmon (https://sketchfab.com/shedmon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/round-table-86091129fc304b5d951dbd5352dcb04f
Title: Round Table
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Table(props) {
  const { nodes, materials } = useGLTF('/round_table.glb')
  return (
    <group {...props} dispose={null}>
      <mesh receiveShadow geometry={nodes.Object_2.geometry} material={materials.Default} rotation={[-Math.PI / 2, 0, 0]} scale={0.002} />
    </group>
  )
}

useGLTF.preload('/round_table.glb')
